Updated layout of dialogs and updated labels
FedoraQt/MediaWriter pull request #424
Opened 2022-04-21 13:30 UTC by gastoner

Fixes #420 
Fixes #421 
Fixes #423

2022-04-21 15:11 UTC, grulja requested changes

2022-04-21 15:11 UTC, grulja commented on src/app/qml/DownloadPage.qml
> +                text: qsTr("Restart and boot from %1 to start using Fedora Workstation.").arg(drives.selected ? drives.selected.readableSize : "N/A")
Users won't be downloading only Fedora Workstation.

2022-04-22 09:18 UTC, gastoner commented
Fixes #278

2022-04-22 10:55 UTC, grulja requested changes

2022-04-22 10:55 UTC, grulja commented on src/app/qml/CancelDialog.qml
> +                        qsTr("Download progress will be lost and media writing will be aborted?")
This shouldn't end with a questionmark.

2022-04-22 10:55 UTC, grulja commented on src/app/qml/CancelDialog.qml
> +                        qsTr("Writing process will be aborted and your drive will have to be restored afterwards?")
Same here.

2022-04-22 10:55 UTC, grulja commented on src/app/qml/DownloadPage.qml
> +
Remove redundant new line

2022-04-22 11:16 UTC, merged